apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-app
  annotations:
    nginx.ingress.kubernetes.io/reqrite-targer: /
spec:
  ingressClassName: nginx
  rules:
  - host: web-app.techwithsrujan.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-web-app
            port:
              number: 80